### ISSUE TITLE
to_trait_object posssibly unsound

### ISSUE THREAD

**Issue by nico-abram** [fkoep/downcast-rs#5]
I'm referring to https://github.com/fkoep/downcast-rs/blob/master/src/lib.rs#L107-L117

One thing that seems scary, is it's relying on the internal layout of https://doc.rust-lang.org/std/raw/struct.TraitObject.html . This is nightly specifically because it's not stable (See https://github.com/rust-lang/rust/issues/27751 ) , so if the layout were to change for whatever reason (However unlikely) it would probably break this horribly (And what's more, it would probably work fine on some compiler versions but not others, and possibly not break with just a guaranteed panic but with memory-unsafety/UB).

The assert `assert_eq!(mem::size_of::<&T>(), mem::size_of::<TraitObject>());` doesn't feel sufficient to me to guarantee that what is being done is safe. If I recall correctly, slices references(Which satisfy the :?Sized check) have the same size but mean a completely different thing.

Nemo157 on the community discord's #black-magic channel pointed out `TraitObject` also must be repr(C) for there to be any layout guarantees about it (Reordering, etc).

**Comment by fkoep** [comment]
Yes, even 2 years later this is still the case.

There needs something to be done here, if possible.
However, having been absend of Rust for a few years, i don't know if modern Rust offers any solution yet.
_Possibly_, in future, one could at least add a negative bound like `T: for<E> !SliceIndex<E>`... which would just be a hack for fixing the slice-reference-issue.

At the moment, there does not seem a way to downcast trait objects to trait objects in safe rust.
The more actively maintained `downcast-rs` crate (unfortunate naming) faces the same problem (https://github.com/marcianx/downcast-rs/issues/10) and choose to omit this functionality.
However, this is something i would like to keep for my own use.

If anyone comes up with a way to do it safely, any information would be really appreciated.

**Comment by fkoep** [comment]
Also, the `TraitObject` struct has now been marked properly as `repr(C)` by jiangliu's PR #4.

**Comment by fkoep-ses** [comment]
There does seem to be a possible solution in sight on nightly rust :

https://doc.rust-lang.org/nightly/std/ptr/index.html (`Metadata`, `Pointee`, and associated....) 

Which are intended to replace `TraitObject`.

See here for the corresponding RFC: https://rust-lang.github.io/rfcs/2580-ptr-meta.html

**Comment by fkoep** [comment]
This has been resolved with 0.11 as `downcast` does not rely on unsafe casts anymore.
