### ISSUE TITLE
clippy warns about unsafe functions missing Safety section

### ISSUE THREAD

**Issue by asomers** [fkoep/downcast-rs#6]
The latest clippy (rustc nightly 1.41.0) warns that downcast's generated methods lack a `# Safety` section in their docs.  The appropriate course of action would probably be to silence the warning with `#![allow(clippy::missing_safety_doc)]`.

**Comment by fkoep** [comment]
This has been fixed in https://github.com/fkoep/downcast-rs/commit/c4e2aad310228cd4c7d03f3bb7abb69d81af2a9c
